//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STech_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MegamenuItem
    {
        public int Id { get; set; }
        public string MegamenuItemName { get; set; }
        public string MegamenuItemLink { get; set; }
        public int MegamenuId { get; set; }
    
        public virtual Megamenu Megamenu { get; set; }
    }
}
